// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_NLP_H
#define ROOTELEMENT_NLP_H

/************************************************************
 NLP class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "RootElement/String.h"
#include "RootElement/Triplet.h"

/************************************************************/
/**
 * 
 */
class NLP {
public:

	/**
	 * 
	 * @param sentence 
	 * @return  
	 */
	Triplet sentence2triplets(String /*in*/sentence);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of NLP class header
 ************************************************************/

#endif
