// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_NLP_BODY

/************************************************************
 NLP class body
 ************************************************************/

// include associated header file
#include "RootElement/NLP.h"

// Derived includes directives

// static attributes (if any)

/**
 * 
 * @param sentence 
 * @return  
 */
Triplet NLP::sentence2triplets(String /*in*/sentence) {
}

/************************************************************
 End of NLP class body
 ************************************************************/
