// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_Perceptron_BODY

/************************************************************
 Perceptron class body
 ************************************************************/

// include associated header file
#include "RootElement/Perceptron.h"

// Derived includes directives

// static attributes (if any)

/**
 * 
 * @param input 
 * @return  
 */
Real Perceptron::compute(Real /*in*/input) {
}

/**
 * 
 * @param input 
 * @param error 
 * @return Real 
 */
Real Perceptron::train(Real /*in*/input, Real /*in*/error) {
}

/************************************************************
 End of Perceptron class body
 ************************************************************/
