// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_QL_BODY

/************************************************************
 QL class body
 ************************************************************/

// include associated header file
#include "RootElement/QL.h"

// Derived includes directives

// static attributes (if any)

/**
 * 
 * @param null 
 * @return  
 */
Triplet QL::ql(Triplet /*in*/null) {
}

/************************************************************
 End of QL class body
 ************************************************************/
