// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_QL_H
#define ROOTELEMENT_QL_H

/************************************************************
 QL class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "RootElement/Perceptron.h"
#include "RootElement/Triplet.h"
#include "RootElement/Triplet.h"

/************************************************************/
/**
 * 
 */
class QL {
public:
	/**
	 * 
	 */
	Perceptron* perceptron[];

	/**
	 * 
	 * @param null 
	 * @return  
	 */
	Triplet ql(Triplet /*in*/null);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of QL class header
 ************************************************************/

#endif
