// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_Samu_BODY

/************************************************************
 Samu class body
 ************************************************************/

// include associated header file
#include "RootElement/Samu.h"

// Derived includes directives

// static attributes (if any)

/**
 * 
 */
void Samu::FamilyCaregiverShell() {
}

/**
 * 
 */
void Samu::NetworkCaregiverShell() {
}

/************************************************************
 End of Samu class body
 ************************************************************/
