// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_SAMU_H
#define ROOTELEMENT_SAMU_H

/************************************************************
 Samu class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "RootElement/NLP.h"

/************************************************************/
/**
 * 
 */
class Samu {
public:
	/**
	 * 
	 */
	NLP nlp;

	/**
	 * 
	 */
	void FamilyCaregiverShell();

	/**
	 * 
	 */
	void NetworkCaregiverShell();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Samu class header
 ************************************************************/

#endif
