// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_SPOTriplet_BODY

/************************************************************
 SPOTriplet class body
 ************************************************************/

// include associated header file
#include "RootElement/SPOTriplet.h"

// Derived includes directives

// static attributes (if any)

/************************************************************
 End of SPOTriplet class body
 ************************************************************/
