// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_SPOTRIPLET_H
#define ROOTELEMENT_SPOTRIPLET_H

/************************************************************
 SPOTriplet class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "RootElement/String.h"
#include "RootElement/String.h"
#include "RootElement/String.h"

/************************************************************/
/**
 * 
 */
class SPOTriplet {
public:
	/**
	 * 
	 */
	String S;
	/**
	 * 
	 */
	String P;
	/**
	 * 
	 */
	String O;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of SPOTriplet class header
 ************************************************************/

#endif
